name: ticket_system
description: A ticket management system
publish_to: 'none'

environment:
  sdk: '^3.3.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
